In [1]:
import numpy as np

# 1차원 배열 생성
array1 = np.array([1, 2, 3])

# 2차원 배열 생성
array2 = np.array([[1, 2, 3],
                   [4, 5, 6]])


In [ ]:
sequence_array = np.arange(10)  ## 얘는 10행 0열??
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)


[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [3]:
list1 = [1, 2, 3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)


<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [4]:
zero_array = np.zeros((3,2), dtype = 'int32')
zero_array

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [5]:
array2 = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("array2:")
print(array2)
print("Shape:", array2.shape)
print("차원 수 (ndim):", array2.ndim)


array2:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
차원 수 (ndim): 2


axis = 0은 가장 바깥쪽이다.
따라서 2차원의 경우 axis = 0은 컬럼을 의미한다. -> [0]을 찍으면 첫번째 열의 로우라는 의미
(1차원일 때는 로우) -> 인덱싱[0]을 찍으면 로우의 첫번째 값이 나옴

shape을 찍을 때 나오는 (2,3)의 [0]인 2는 로우가 몇 줄인지와 열의 길이를 의미한다

In [ ]:
array1 = np.arange(20)
print('array1:\n', array1)

# (2, 5)로 reshape
array2 = array1.reshape(4, 5)
print('array2:\n', array2)

# (5, 2)로 reshape
array3 = array1.reshape(2, 10)
print('array3:\n', array3)

# (4, 3)으로 reshape 시도 - 오류 발생
# array1.reshape(4, 3)  # ValueError 발생

array1:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
array2:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
array3:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [18]:
array1 = np.arange(10)

# 자동 계산 가능한 경우
array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)

array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)

# 자동 계산 불가능한 경우 - 오류 발생
# array4 = array1.reshape(-1, 4)  # ValueError 발생

array2 shape: (2, 5)
array3 shape: (5, 2)


## Pandas와 Numpy

In [19]:
import numpy as np
import pandas as pd

s = pd.Series([1, 3, 5, np.nan, 6, 8])
print(s)


0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [21]:
dates = pd.date_range("20250912", periods=6)
print(dates)

df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
print(df)


DatetimeIndex(['2025-09-12', '2025-09-13', '2025-09-14', '2025-09-15',
               '2025-09-16', '2025-09-17'],
              dtype='datetime64[ns]', freq='D')
                   A         B         C         D
2025-09-12  0.119786 -1.421020 -0.102000 -2.071908
2025-09-13 -0.751239  1.738842  0.036421  1.278074
2025-09-14 -1.230203 -0.371744  0.637666 -0.808616
2025-09-15 -0.048940  0.519080 -0.943735  0.294014
2025-09-16 -1.277133  0.287848  0.337511  1.086664
2025-09-17 -0.052729  0.039537  1.165871  1.736069


In [26]:
df2 = pd.DataFrame({
    "A": 1.0,
    "B": pd.Timestamp("20130102"),
    "C": pd.Series(1, index=list(range(4)), dtype="int32"),
    "D": np.array([3] * 4, dtype="int32"),
    "E": pd.Categorical(["test", "train", "test", "train"]),
    "F": "foo"
})
print(df2)


     A          B  C  D      E    F
0  1.0 2013-01-02  1  3   test  foo
1  1.0 2013-01-02  1  3  train  foo
2  1.0 2013-01-02  1  3   test  foo
3  1.0 2013-01-02  1  3  train  foo


In [ ]:
print(df2.dtypes)


In [ ]:
print(df.head())     # 상위 5개 행
print(df.tail(3))    # 하위 3개 행


In [ ]:
print(df.index)
print(df.columns)


In [ ]:
print(df.to_numpy())


In [ ]:
print(df.describe())


In [ ]:
print(df.T)


In [ ]:
print(df["A"])

In [ ]:
df[0:3]

In [ ]:
df["20130102":"20130104"]

In [ ]:
df.loc["20130102":"20130104", ["A", "B"]]


In [ ]:
df.loc[dates[0], "A"]       # 위치 기반 접근
df.at[dates[0], "A"]        # 가장 빠른 방식


In [ ]:
df.iloc[3]                  # 4번째 행 전체
df.iloc[3:5, 0:2]           # 4~5번째 행, 1~2번째 열
df.iloc[[1, 2, 4], [0, 2]]  # 특정 행/열 조합
df.iloc[1:3, :]             # 2~3번째 행, 전체 열
df.iloc[:, 1:3]             # 전체 행, 2~3번째 열
df.iloc[1, 1]               # 2행 2열 값
df.iat[1, 1]                # 빠른 2행 2열 접근


In [ ]:
df[df["A"] > 0]             # A 열이 0보다 큰 행만

df[df > 0]                 # 전체 DataFrame에서 양수만 표시, 나머지는 NaN


In [ ]:
df2 = df.copy()
df2["E"] = ["one", "one", "two", "three", "four", "three"]

df2[df2["E"].isin(["two", "four"])]


In [ ]:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ["E"])
df1.loc[dates[0] : dates[1], "E"] = 1
print(df1)


In [ ]:
# 결측치가 있는 모든 행 제거
df1.dropna(how="any")

# 결측치를 5로 채우기
df1.fillna(value=5)


In [ ]:
pd.isna(df1)

## 데이터 처리와 집계

In [ ]:
import pandas as pd

# Titanic 데이터 CSV 파일 로드
titanic_df = pd.read_csv("../data/titanic.csv")

# DataFrame 출력
titanic_df

In [ ]:
# 이름 기준 오름차순 정렬
titanic_sorted = titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)

# Pclass와 Name 기준 내림차순 정렬
titanic_sorted = titanic_df.sort_values(by=['Pclass', 'Name'], ascending=False)
titanic_sorted.head(3)


In [ ]:
print(titanic_df['Pclass'].nunique())
print(titanic_df['Survived'].nunique())
print(titanic_df['Name'].nunique())

In [ ]:
titanic_df.count()

In [ ]:
# 평균
titanic_df[['Age', 'Fare']].mean()

# 합계
titanic_df[['Age', 'Fare']].sum()

# 최솟값
titanic_df[['Age', 'Fare']].min()


In [ ]:
# groupby 객체 생성
titanic_groupby = titanic_df.groupby('Pclass')

# Age와 Fare에 대해 count
titanic_groupby[['Age', 'Fare']].count()


In [ ]:
# 최대값과 최소값을 나란히 출력
titanic_df.groupby('Pclass')['Age'].max(), titanic_df.groupby('Pclass')['Age'].min()


In [ ]:
# max, min 함께 보기
titanic_df.groupby('Pclass')['Age'].agg([max, min])


In [ ]:
titanic_df.groupby(['Pclass']).agg(
    age_max=('Age', 'max'),
    age_mean=('Age', 'mean'),
    fare_mean=('Fare', 'mean')
)


In [ ]:
agg_format = {
    'Age': 'max',
    'SibSp': 'sum',
    'Fare': 'mean'
}
titanic_df.groupby('Pclass').agg(agg_format)


In [ ]:
# 이름의 길이 계산
titanic_df['Name_len'] = titanic_df['Name'].apply(lambda x: len(x))
titanic_df[['Name', 'Name_len']].head(3)


In [ ]:
# 나이 기준으로 아동/성인 구분
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x: 'Child' if x <= 15 else 'Adult')
titanic_df[['Age', 'Child_Adult']].head(8)


In [ ]:
def categorize_age(age):
    """
    나이에 따라 연령대를 분류하는 함수
    """
    if age <= 5:
        return 'Baby'
    elif age <= 12:
        return 'Child'
    elif age <= 18:
        return 'Teenager'
    elif age <= 25:
        return 'Student'
    elif age <= 35:
        return 'Young Adult'
    elif age <= 60:
        return 'Adult'
    else:
        return 'Elderly'

# 적용 및 확인
titanic_df['Age_cate'] = titanic_df['Age'].apply(categorize_age)
titanic_df[['Age', 'Age_cate']].head()


## 데이터 병합 및 변환 이론

In [ ]:
import pandas as pd

df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                    'B': ['B0', 'B1', 'B2']})

df2 = pd.DataFrame({'C': ['C0', 'C1', 'C2'],
                    'D': ['D0', 'D1', 'D2']})

df3 = pd.concat([df1, df2], axis=0)  # 행 병합
df4 = pd.concat([df1, df2], axis=1)  # 열 병합

print(df1)
print('\n')
print(df2)
print('\n')
print(df3)
print('\n')
print(df4)


In [ ]:
import pandas as pd

df1 = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                    'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3']})

df2 = pd.DataFrame({'key': ['K0', 'K1', 'K2'],
                    'C': ['C0', 'C1', 'C2'],
                    'D': ['D0', 'D1', 'D2']})

df_merged = pd.merge(df1, df2, on='key', how='inner')

print(df1)
print('\n')
print(df2)
print('\n')
print(df_merged)


In [ ]:
import pandas as pd

df1 = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                    'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3']})

df2 = pd.DataFrame({'key': ['K0', 'K1', 'K2'],
                    'C': ['C0', 'C1', 'C2'],
                    'D': ['D0', 'D1', 'D2']})

df_merged = pd.merge(df1, df2, on='key', how='outer')

print(df1)
print('\n')
print(df2)
print('\n')
print(df_merged)


In [ ]:
import pandas as pd

df1 = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                    'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3']})

df2 = pd.DataFrame({'key': ['K0', 'K1', 'K2'],
                    'C': ['C0', 'C1', 'C2'],
                    'D': ['D0', 'D1', 'D2']})

df_merged = pd.merge(df1, df2, on='key', how='left')

print(df1)
print('\n')
print(df2)
print('\n')
print(df_merged)


In [ ]:
import pandas as pd

df1 = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                    'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3']})

df2 = pd.DataFrame({'key': ['K0', 'K1', 'K2'],
                    'C': ['C0', 'C1', 'C2'],
                    'D': ['D0', 'D1', 'D2']})

df_merged = pd.merge(df1, df2, on='key', how='right')

print(df1)
print('\n')
print(df2)
print('\n')
print(df_merged)


In [ ]:
import pandas as pd

df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2']
}, index=['K0', 'K1', 'K2'])

df2 = pd.DataFrame({
    'C': ['C0', 'C1', 'C2'],
    'D': ['D0', 'D1', 'D2']
}, index=['K0', 'K2', 'K3'])

df_merged = df1.join(df2, how='left')

print(df1)
print('\n')
print(df2)
print('\n')
print(df_merged)


In [ ]:
sales = pd.DataFrame({
    'customer_id': [1, 2, 3, 4],
    'product_id': [101, 102, 103, 104],
    'quantity': [5, 2, 3, 1]
})

customers = pd.DataFrame({
    'customer_id': [1, 2, 3, 5],
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'city': ['Seoul', 'Busan', 'Daegu', 'Incheon']
})

sales = sales.set_index('customer_id')
customers = customers.set_index('customer_id')

merged_data = sales.join(customers, how='left')

print(sales)
print('\n')
print(customers)
print('\n')
print(merged_data)


In [ ]:
df1 = pd.DataFrame({
    'key': ['K0', 'K1', 'K2', 'K3'],
    'A': ['A0', 'A1', 'A2', 'A3'],
    'C': ['C0', 'C1', 'C2', 'C3']
})

df2 = pd.DataFrame({
    'key': ['K0', 'K1', 'K2'],
    'C': ['C4', 'C5', 'C6'],
    'D': ['D0', 'D1', 'D2']
})

df_merged = pd.merge(df1, df2, on='key', how='inner', suffixes=('_left', '_right'))

print(df1)
print('\n')
print(df2)
print('\n')
print(df_merged)


In [ ]:
df1 = pd.DataFrame({
    'key': ['K0', 'K1', 'K2', 'K3'],
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3']
})

df2 = pd.DataFrame({
    'key': ['K0', 'K1', 'K2'],
    'C': ['C0', 'C1', 'C2'],
    'D': ['D0', 'D1', 'D2']
})

df_merged = pd.merge(df1, df2, on='key', how='inner')
df_merged = df_merged.drop('B', axis=1)

print(df1)
print('\n')
print(df2)
print('\n')
print(df_merged)


In [ ]:
df1 = pd.DataFrame({
    'key1': ['K0', 'K1', 'K2', 'K3'],
    'key2': ['K4', 'K5', 'K6', 'K7'],
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3']
})

df2 = pd.DataFrame({
    'key1': ['K0', 'K1', 'K2'],
    'key2': ['K4', 'K5', 'K6'],
    'C': ['C0', 'C1', 'C2'],
    'D': ['D0', 'D1', 'D2']
})

df_merged = pd.merge(df1, df2, on=['key1', 'key2'], how='inner')

print(df1)
print('\n')
print(df2)
print('\n')
print(df_merged)


In [ ]:
import pandas as pd

# Titanic 데이터 CSV 파일 로드
replace_test_df = pd.read_csv("../data/titanic.csv")

In [ ]:
import numpy as np

# 예: Titanic 데이터
replace_test_df['Sex'] = replace_test_df['Sex'].replace({'male': 'Man', 'female': 'Woman'})
print(replace_test_df.head(10))


In [ ]:
# NaN을 특정 값으로 대체
replace_test_df['Cabin'] = replace_test_df['Cabin'].replace(np.nan, 'CXXX')

# Cabin별 값 개수 확인
print(replace_test_df['Cabin'].value_counts(dropna=False))